// src/lib/questions.ts
import type { FormStep } from '@/types/spa';

export const FORM_STEPS: FormStep[] = [
  {
    id: 1,
    title: 'Student Information',
    description: "Let's start with some basic details about the student.",
    questions: [
      {
        id: 'studentName',
        text: 'Student Full Name',
        type: 'text',
        required: true,
      },
      {
        id: 'class',
        text: 'Class / Grade',
        type: 'single',
        required: true,
        options: [
          { value: '6', label: 'Class 6' },
          { value: '7', label: 'Class 7' },
          { value: '8', label: 'Class 8' },
          { value: '9', label: 'Class 9' },
          { value: '10', label: 'Class 10' },
        ],
      },
      {
        id: 'schoolName',
        text: 'School Name',
        type: 'text',
        required: false,
      },
      {
        id: 'parentName',
        text: "Parent / Guardian's Name",
        type: 'text',
        required: false,
      },
      {
        id: 'parentContact',
        text: 'Parent Contact Number',
        type: 'text',
        required: false,
      },
      {
        id: 'studentEmail',
        text: 'Email Address (for report delivery)',
        type: 'text',
        required: false,
      },
    ],
  },
  {
    id: 2,
    title: 'Academic Background',
    description: 'Tell us about your current academic situation.',
    questions: [
      {
        id: 'q1',
        text: 'How would you describe your recent academic performance?',
        type: 'single',
        required: true,
        options: [
          { value: 'Excellent', label: 'Excellent' },
          { value: 'Good', label: 'Good' },
          { value: 'Average', label: 'Average' },
          { value: 'Below Average', label: 'Below Average' },
          { value: 'Poor', label: 'Poor' },
        ],
      },
      {
        id: 'q2',
        text: 'Which subjects do you currently find most difficult? (Select all that apply)',
        type: 'multi',
        required: false,
        options: [
          { value: 'Mathematics', label: 'Mathematics' },
          { value: 'Science', label: 'Science' },
          { value: 'English', label: 'English' },
          { value: 'Social Science', label: 'Social Science' },
          { value: 'Hindi', label: 'Hindi' },
          { value: 'Other', label: 'Other' },
        ],
      },
      {
        id: 'q3',
        text: "What is the biggest academic challenge you're facing right now?",
        type: 'single',
        required: true,
        options: [
          { value: 'Understanding concepts', label: 'Understanding concepts' },
          { value: 'Forgetting what I study', label: 'Forgetting what I study' },
          { value: 'Lack of focus', label: 'Lack of focus' },
          { value: 'Exam anxiety', label: 'Exam anxiety' },
          { value: 'Poor time management', label: 'Poor time management' },
          { value: 'Inconsistent study habits', label: 'Inconsistent study habits' },
          { value: 'Homework backlog', label: 'Homework backlog' },
        ],
      },
      {
        id: 'q4',
        text: 'Do you currently attend any tuition or coaching?',
        type: 'boolean',
        required: true,
      },
    ],
  },
  {
    id: 3,
    title: 'Concept Clarity',
    description: 'How well do you understand and grasp new topics?',
    questions: [
      {
        id: 'q10',
        text: 'When a new topic is taught in school, how quickly do you understand it?',
        type: 'single',
        required: true,
        options: [
          { value: 'Immediately', label: 'Immediately' },
          { value: 'Mostly', label: 'Mostly on first explanation' },
          { value: 'Sometimes', label: 'Sometimes, with effort' },
          { value: 'Rarely', label: 'Rarely, need lots of help' },
          { value: 'Almost Never', label: 'Almost never' },
        ],
      },
      {
        id: 'q11',
        text: 'When solving questions, how often do you understand why the answer is correct?',
        type: 'single',
        required: true,
        options: [
          { value: 'Always', label: 'Always' },
          { value: 'Often', label: 'Often' },
          { value: 'Sometimes', label: 'Sometimes' },
          { value: 'Rarely', label: 'Rarely' },
          { value: 'Never', label: 'Never' },
        ],
      },
      {
        id: 'q12',
        text: 'If someone asks you to explain a concept you learned recently, how confident are you?',
        type: 'single',
        required: true,
        options: [
          { value: 'Very Confident', label: 'Very Confident' },
          { value: 'Confident', label: 'Confident' },
          { value: 'Neutral', label: 'Neutral' },
          { value: 'Not Very Confident', label: 'Not Very Confident' },
          { value: 'Not Confident At All', label: 'Not Confident At All' },
        ],
      },
    ],
  },
  {
    id: 4,
    title: 'Knowledge Retention',
    description: 'How well do you remember what you have studied?',
    questions: [
      {
        id: 'q13',
        text: 'After studying a chapter, how much do you remember one week later?',
        type: 'single',
        required: true,
        options: [
          { value: 'Almost Everything', label: 'Almost Everything' },
          { value: 'Most Things', label: 'Most Things' },
          { value: 'About Half', label: 'About Half' },
          { value: 'Very Little', label: 'Very Little' },
          { value: 'Almost Nothing', label: 'Almost Nothing' },
        ],
      },
      {
        id: 'q14',
        text: 'Before exams, how often do you feel you have forgotten previously studied topics?',
        type: 'single',
        required: true,
        options: [
          { value: 'Never', label: 'Never — I remember everything' },
          { value: 'Rarely', label: 'Rarely' },
          { value: 'Sometimes', label: 'Sometimes' },
          { value: 'Often', label: 'Often' },
          { value: 'Very Often', label: 'Very Often' },
        ],
      },
      {
        id: 'q15',
        text: 'How frequently do you revise old chapters?',
        type: 'single',
        required: true,
        options: [
          { value: 'Weekly', label: 'Weekly' },
          { value: 'Every Two Weeks', label: 'Every Two Weeks' },
          { value: 'Monthly', label: 'Monthly' },
          { value: 'Only Before Exams', label: 'Only Before Exams' },
          { value: 'Almost Never', label: 'Almost Never' },
        ],
      },
    ],
  },
  {
    id: 5,
    title: 'Focus & Attention',
    description: 'Understanding how well you concentrate while studying.',
    questions: [
      {
        id: 'q16',
        text: 'How long can you study with full concentration without taking a break?',
        type: 'single',
        required: true,
        options: [
          { value: 'More than 60 minutes', label: 'More than 60 minutes' },
          { value: '45–60 minutes', label: '45–60 minutes' },
          { value: '30–45 minutes', label: '30–45 minutes' },
          { value: '15–30 minutes', label: '15–30 minutes' },
          { value: 'Less than 15 minutes', label: 'Less than 15 minutes' },
        ],
      },
      {
        id: 'q17',
        text: 'What usually distracts you the most while studying?',
        type: 'single',
        required: true,
        options: [
          { value: 'Nothing Major', label: 'Nothing Major' },
          { value: 'Noise Around Me', label: 'Noise Around Me' },
          { value: 'Friends', label: 'Friends' },
          { value: 'Daydreaming', label: 'Daydreaming' },
          { value: 'Gaming', label: 'Gaming' },
          { value: 'YouTube/Reels', label: 'YouTube/Reels' },
          { value: 'Mobile Phone', label: 'Mobile Phone' },
        ],
      },
      {
        id: 'q18',
        text: 'During classes, how often does your mind wander to other things?',
        type: 'single',
        required: true,
        options: [
          { value: 'Never', label: 'Never — fully focused' },
          { value: 'Rarely', label: 'Rarely' },
          { value: 'Sometimes', label: 'Sometimes' },
          { value: 'Often', label: 'Often' },
          { value: 'Very Often', label: 'Very Often' },
        ],
      },
    ],
  },
  {
    id: 6,
    title: 'Consistency & Discipline',
    description: 'How regular and disciplined are you in your studies?',
    questions: [
      {
        id: 'q19',
        text: 'How often do you follow a fixed study schedule?',
        type: 'single',
        required: true,
        options: [
          { value: 'Always', label: 'Always follow it' },
          { value: 'Usually', label: 'Usually' },
          { value: 'Sometimes', label: 'Sometimes' },
          { value: 'Rarely', label: 'Rarely' },
          { value: 'Never', label: 'No fixed schedule' },
        ],
      },
      {
        id: 'q20',
        text: 'How often do you miss planned study sessions?',
        type: 'single',
        required: true,
        options: [
          { value: 'Never', label: 'Never miss them' },
          { value: 'Rarely', label: 'Rarely' },
          { value: 'Sometimes', label: 'Sometimes' },
          { value: 'Often', label: 'Often' },
          { value: 'Very Often', label: 'Very Often' },
        ],
      },
      {
        id: 'q21',
        text: 'How regularly do you complete homework on time?',
        type: 'single',
        required: true,
        options: [
          { value: 'Always', label: 'Always' },
          { value: 'Usually', label: 'Usually' },
          { value: 'Sometimes', label: 'Sometimes' },
          { value: 'Rarely', label: 'Rarely' },
          { value: 'Never', label: 'Never' },
        ],
      },
    ],
  },
  {
    id: 7,
    title: 'Exam Readiness',
    description: 'How prepared are you when it comes to tests and exams?',
    questions: [
      {
        id: 'q22',
        text: 'How confident do you feel before tests and exams?',
        type: 'single',
        required: true,
        options: [
          { value: 'Very Confident', label: 'Very Confident' },
          { value: 'Confident', label: 'Confident' },
          { value: 'Neutral', label: 'Neutral' },
          { value: 'Slightly Nervous', label: 'Slightly Nervous' },
          { value: 'Very Nervous', label: 'Very Nervous' },
        ],
      },
      {
        id: 'q23',
        text: 'When you encounter a difficult question in an exam, what usually happens?',
        type: 'single',
        required: true,
        options: [
          { value: 'I stay calm and attempt it', label: 'Stay calm and attempt it' },
          { value: 'I try but lose confidence', label: 'Try but lose confidence' },
          { value: 'I panic slightly', label: 'Panic slightly' },
          { value: 'I often get stuck', label: 'Often get stuck' },
          { value: 'I completely freeze', label: 'Completely freeze' },
        ],
      },
      {
        id: 'q24',
        text: 'How often do you solve sample papers, worksheets or practice tests?',
        type: 'single',
        required: true,
        options: [
          { value: 'Weekly', label: 'Weekly' },
          { value: 'Twice a Month', label: 'Twice a Month' },
          { value: 'Monthly', label: 'Monthly' },
          { value: 'Rarely', label: 'Rarely' },
          { value: 'Never', label: 'Never' },
        ],
      },
    ],
  },
  {
    id: 8,
    title: 'Self-Testing & Improvement',
    description: 'Do you take initiative to test yourself and learn from mistakes?',
    questions: [
      {
        id: 'q25',
        text: 'After making mistakes, how often do you review and learn from them?',
        type: 'single',
        required: true,
        options: [
          { value: 'Always', label: 'Always — I review every mistake' },
          { value: 'Often', label: 'Often' },
          { value: 'Sometimes', label: 'Sometimes' },
          { value: 'Rarely', label: 'Rarely' },
          { value: 'Never', label: 'Never' },
        ],
      },
      {
        id: 'q26',
        text: 'Do you maintain any notebook or record of your mistakes?',
        type: 'single',
        required: true,
        options: [
          { value: 'Yes, consistently', label: 'Yes, I maintain it consistently' },
          { value: 'Sometimes', label: 'Sometimes' },
          { value: 'No', label: 'No, I don\'t' },
        ],
      },
      {
        id: 'q27',
        text: 'How often do you test yourself without being asked by a teacher?',
        type: 'single',
        required: true,
        options: [
          { value: 'Weekly', label: 'Weekly' },
          { value: 'Twice a Month', label: 'Twice a Month' },
          { value: 'Monthly', label: 'Monthly' },
          { value: 'Rarely', label: 'Rarely' },
          { value: 'Never', label: 'Never' },
        ],
      },
    ],
  },
  {
    id: 9,
    title: 'Your Goals',
    description: 'Tell us what you want to achieve and what matters most to you.',
    questions: [
      {
        id: 'q28',
        text: 'What is your primary goal this academic year?',
        type: 'single',
        required: true,
        options: [
          { value: 'Improve marks', label: 'Improve my marks' },
          { value: 'Build stronger concepts', label: 'Build stronger concepts' },
          { value: 'Prepare for Olympiads', label: 'Prepare for Olympiads' },
          { value: 'Gain confidence', label: 'Gain confidence' },
          { value: 'Improve study habits', label: 'Improve study habits' },
          { value: 'Other', label: 'Other' },
        ],
      },
      {
        id: 'q29',
        text: 'If one thing could improve immediately in your studies, what would you want it to be?',
        type: 'text',
        required: false,
      },
      {
        id: 'q30',
        text: 'Is there anything else you would like us to know about your learning journey?',
        type: 'text',
        required: false,
      },
    ],
  },
];

export const TOTAL_STEPS = FORM_STEPS.length;
